----Database initialization
--create table if not exists test_user(
--    id int auto_increment primary key not null,
--    name varchar(20) not null,
--    email varchar(20) not null
--);
--
--insert into test_user(name, email) values
--('John', 'jon@gmail.com'),
--('sam','sam@gmail.com'),
--('rudy','rudy@gmail.com');
--
----create table